### ISSUE TITLE
A fix to the LAN code

### ISSUE THREAD

**Issue by Sir-LoLz** [Sir-LoLz/Improve-MKDD-netcode#1]
So a very underrated feature for Mario Kart Double Dash is it’s LAN mode. As one of the few of us who have played it I can attest that it is a blast to play and has a charm about it that later entries in the Mario Kart franchise have yet to match.

Using Xlink Kai it is possible to tunnel the game over the internet. However the netcode was not designed with this in mind and has a tendency to crash. And even if it does not crash it will run in slow motion due to the lockstep nature of it. This is a great shame to an otherwise great game.

I made this Github post so I can post a bounty to fix the issue. My desire is to see a fix developed that can be patched to a legally dumped ISO file that will remove the crashes that happen during menu transitions and remove the slowdown that happens during the race. Whether this is with AR codes, code patches, or other does not matter as long as the issues are mitigated. Either through a recoding, or an increase to the network buffer the resides in the code.

**Comment by ewuc** [comment]
Hi, I'm from bountysource for bounty.
@Sir-LoLz 

* XLink Kai enables online play by simulating a LAN over the internet. This is not how Dolphin's NetPlay works.
* XLink Kai will only work with games that support LAN play.
* Dolphin's NetPlay will work with any game.


## If using Netplay:
1. Make all players have exactly the same game. (NTSC/PAL, they used the same download link)
2. The Game ISO should be set up inside emulator, so when emulator is opened it shows the game.
3. Make all players have exactly the same memory card. (Config -> GameCube -> Device Settings -> Slot A Memory Card) 
Rename your card so you can remember and send your Memory card to your friends and make them load memory card to slot A.
4. Make all players have exactly the same cheats/ AR codes enabled
5. In Netplay select Traversal Server
6. Before clicking Start in netplay window, increase Buffer from 5 to 18 or so, (depending on the Ping between you and your partner. 1 Buffer per 8 ms. If ping shown is 50ms, buffer is 50/8 = 7, use 7) If there is bad connection it will lag, so this helps. For best experience, should be lower than 20.
7. In MKDD I recommend having everyone not use memory cards and enable the unlock everything cheat code. Also make everyone try 30fps AR Code below. Only activate one fps code!
8. All players must use the same Dolphin version. Its best to use the latest beta versions from the official website. It best to be isolated from your main Dolphin profile by creating empty "portable.txt" file where Dolphin.exe is located.
9. Rule of thumb is that most settings should be set to default, because Dolphin 5.0 Netplay is still buggy. I think XLink Kai setup is better for this game. 

## If using XLink Kai setup:

* Make a proper Dolphin setup trough BBA (Nintendo GameCube Broadband Adapter) tunneling through XLink Kai
* Dolphin 5.0-12233 or higher is required
* [Dolphin_Gamecube_XLink_BBA_Tutorial](https://www.teamxlink.co.uk/wiki/Dolphin_Gamecube_XLink_BBA_Tutorial)

### Basically there are two ways 

#### 1. If the two Dolphin instances are not running on the same PC as the XLink Kai client (only for local network)

This is how you get 2 Dolphins on 2 Computers connected trough LAN. Both PC's are connected to the local network (same router at home)

 1: Download and make an account for XLink Kai. Make sure it is running in the background. BBA configuration. (Only do it on **one** of the two computers)
 2: In Dolphin settings go to the GameCube tab and set the SP1 option to "broadband adapter (XLink Kai)" (Do this for **both-two** computers)
 3: Only on the computer **that is running Xlink Kai,** get your IPV4 address we need for next step. (If you have DHCP enabled it can change every time) Example: 192.168.1.40
 4: Only on the computer **not running XLink Kai**, the computer we didn't make 1st step. Click the box with the 3 dots next to the SP1 option (Dolphin settings, GameCube tab). Set the field to the IPV4 address noted from above step.
 5: If not done already. make sure both PC's are connected to the same router.
 6. Make sure the firewall on the PC isn't blocking the connection to XLink Kai!
It should work at this point. Start a LAN mode on both computers.


#### 2. You set up two Dolphin emulators on the same computer

The computer is using one XLink Kai client, connected via LAN tunneling, and the rest join via a screen-sharing program called Parsec. 
- This will allow you to host five to eight players on one machine for local or online play. There are a couple things to keep in mind otherwise you will get freezes.
- Each Dolphin instance should be portable so it has own config/settings location, which allows to set up a unique BBA mac address. You can set this in Dolphin.ini or by changing your BBA type to TAP, editing the MAC address, then changing it back to XLink Kai BBA. If you are entering a MAC address by hand keep in mind it must begin with 00:09:bf or 00:17:ab
- Enable the Broadband adapter in both emulators inside Dolphin settings. Open settings and navigate to the GameCube tab. In SP1 enable the Broadband Adapter (Xlink Kai)
- In both Dolphins controller settings make sure background input is enabled.
- Each Dolphin instance must have exactly the same memory card. (Config -> GameCube -> Device Settings -> Slot A Memory Card). Rename your card, so you can remember and load memory card to slot A. Copy card to another emulator instance and load it to to slot A as well.
- Each Dolphin instance must have the same version of the game (PAL/NTSC)
- Each Dolphin instance must have the same cheats or AR codes enabled. Try to use 30fps AR code. Only activate one fps code!
- Open the Host tab in Parsecs settings. Make sure your Virtual Gamepad Type is set to DualShock 4
- Lower the refresh rate on parsec to 30fps
- Lower the PC's screen resolution, so parsec can work better
- Save and then restart Parsec for the code to take effect.
- Make sure XLink Kai is running in the background and that you are logged in.

- Start both Dolphin Emulators. You should see yellow text informing you that the Dolphin has connected to Xlink Kai.





From what I know, MKDD was designed to run at 30fps for USA/NTSC version (25fps if playing EUROPE/PAL version) on split screen multiplayer mode, instead of original 60fps for USA/NTSC version or 50fps if playing EUROPE/PAL version in singleplayer/one screen mode.
So the developers included an internal "frame skip value" in the memory to switch the framerate between 60fps/30fps or 50fps/25fps, which can be also easily ticked by a single-line AR code.


- This significantly lowers the requirement to run the game, also very useful for Android players so the game can be totally playable with low specs hardware if you are willing to play it at 30 FPS or lower.

- The MKDD trough network can be very bandwidth intensive. It is smart to change framerate, to lessen the bandwidth needed, can resolve slow motion.




## You can add AR code with following steps:

1. Navigate to Doplhin emulator installation directory, usually inside Program Files
2. Inside your Dolphin installation dir	(where Dolphin.exe is located) navigate to \Sys\GameSettings\  location and edit file

 - if you have EUROPE/PAL version of the game: edit the file GM4P01.ini and write-append to the end of file the following code, this will give you 4 AR codes for changing framerate:


[ActionReplay_Enabled]
$Force 25 FPS
[ActionReplay]
$Force 50 FPS (default)
044961C8 00000001
$Force 25 FPS
044961C8 00000002
$Force 16 FPS
044961C8 00000003
$Force 12 FPS
044961C8 00000004



 - if you have USA/NTSC version of the game: edit the file GM4E01.ini and write-append to the end of file the following code, this will give you 4 AR codes for changing framerate:

[ActionReplay_Enabled]
$Force 30 FPS
[ActionReplay]
$Force 60 FPS (default)
0448C388 00000001
$Force 30 FPS
0448C388 00000002
$Force 20 FPS
0448C388 00000003
$Force 15 FPS
0448C388 00000004

3. For each emulator instance Enable Cheats inside Dolphin options. (options -> Configure -> Enable Cheats)
4. Then Inside Dolphin menu Tools -> Cheats Manager -> AR Codes, apply Force 30 FPS AR code

**Comment by Sir-LoLz** [comment]
Hello @ewuc !

I appreciate the contribution. but I think there has been a misunderstanding. 

The fix is not for Netplay But for the games LAN mode as I spoke to here ` However the netcode was not designed with this in mind and has a tendency to crash. ` the goal is to get it working with Xlink so that way we can play MKDD 16 players without the need for Netplay inside Dolphin Emulator. 

Also, I am the author of the guide you edited. the source is on my [Discord](https://discord.gg/tuQK4PN).  you can find it [here ](https://cdn.discordapp.com/attachments/403709111566467073/775774087275479070/Dual_Dolphin_on_one_PC_guide.pdf). MKDD naturally runs at 60 FPS. That is why I only included the AR code for 30FPS.

On another note, I ask that you take down the guide. Not trying to accuse your intentions but it is plagiarism of my work. I would prefer you inform me of any errors so I may update them.

**Comment by ewuc** [comment]
Link was removed. As you can see correct code is 00000002 and not 00000022

Do you use US version of the game?
So you don't want 4 emulators running the same time on one PC for 16 players?

**Comment by tarangan** [comment]
is bounty still on

**Comment by Sir-LoLz** [comment]
> is bounty still on

Yes it is. You can message me on discord or join the server. We have some resources that may help

https://discord.gg/YBeEKypUtv

**Comment by MorphicDreamer** [comment]
@Sir-LoLz lol just wondering, is this bounty still open. ;). Such a large bounty and it is amazing that no one has claimed it

**Comment by Sir-LoLz** [comment]
We currently have 2 users developing a fix. but you are welcome to join the discord above and chat with them, :)

**Comment by alvaro-minzala** [comment]
Fixed.
https://github.com/alvaro-minzala/mkdd-lan-fix
Try it yourself before closing the bounty and giving it to me.
You have until February 28, 2022

**Comment by Sir-LoLz** [comment]
@alvaro-minzala I tried that but it is not fixed. so I cannot pay out the bounty for your solution.

**Comment by NekomusuMae** [comment]
In theory this goes against everything the original LAN code was designed for. Honestly, it would probably require scrapping the old LAN code and making a new system from scratch. I am now starting to realize why no one has taken this bounty.

**Comment by abebeos** [comment]
> In theory this goes against everything the original LAN code

Not only the LAN code, but the game code. My understanding is that it is written for near-zero latency (local network), so introducing latency via internet connection results in problems, as the game-code was never tested for this.

**Comment by Sir-LoLz** [comment]
> > In theory this goes against everything the original LAN code
> 
> Not only the LAN code, but the game code. My understanding is that it is written for near-zero latency (local network), so introducing latency via internet connection results in problems, as the game-code was never tested for this.

Yep. That is what the bounty is for! If people can add online play to Smash Brothers Melee- a game that never had netcode to begin with- then I don't see why a game that already has netcode cannot have said netcode expanded to function correctly with higher pings

**Comment by abebeos** [comment]
Not all games are the same. One game-code may have no problems with added latency. Another game-code would need a deeper rewrite, possibly so deep that I could not be done without having the source-codes.

**Comment by Sir-LoLz** [comment]
of course. But my point was that if a game with no netcode could get online added then I see no reason why MKDD cannot. that is why there is a bounty after all.

**Comment by abebeos** [comment]
> I see no reason

that MKDD is differently programmed.

Have you ever seen MKDD working (with any tools/methods/patches etc.) via internet?

**Comment by Sir-LoLz** [comment]
Have you ever seen Super Smash Brothers melee working (with any tools/methods/patches etc.) via internet?

Did not stop people from developing slippi

but on that note yes I have seen MKDD work online even without tools. it just does not work well. which is what this bounty is for. to make it work well. MKDD already works online. it is just not stable.

**Comment by abebeos** [comment]
You may want to setup a smaller bounty for a feasibility/requirements analysis. Could be as low as $250, and would take around 1 week (not fulltime of course), and around one or two hours of your time (mostly answering questions).

You would get a list of possible solution-paths, which would allow potential developers to assess the effort better.

If such an analysis results in "potentially very high effort", then at least you can find your peace, or see to it to proceed differently (e.g. setting up an open project, to start the efforts).

**Comment by Sir-LoLz** [comment]
that is a good idea. I will try to organize that

**Comment by abebeos** [comment]
Re Bountysource, please be aware of this:

https://github.com/abebeos/main/issues/2

**Comment by TZubiri** [comment]
> > > In theory this goes against everything the original LAN code
> > 
> > 
> > Not only the LAN code, but the game code. My understanding is that it is written for near-zero latency (local network), so introducing latency via internet connection results in problems, as the game-code was never tested for this.
> 
> Yep. That is what the bounty is for! If people can add online play to Smash Brothers Melee- a game that never had netcode to begin with- then I don't see why a game that already has netcode cannot have said netcode expanded to function correctly with higher pings

I think melee netplay just works by treating the game as a black box, just relaying controller inputs from one game to another, I'll consult with some tech savvy users to see if we can work out precise details. 

In this sense, melee's approach is easier, since it doesn't necessitate the modification of any existing code. So taking advantage of the existing LAN code might be a red herring.

That said, netplay has been for a long time, it's likely that the naïve solution I'm describing has been developed over time incorporating game-specific optimizations, but I believe that melee netplay has worked for years based on some very simple underlying principle.

**Comment by Sir-LoLz** [comment]
> > > > In theory this goes against everything the original LAN code
> > > 
> > > 
> > > Not only the LAN code, but the game code. My understanding is that it is written for near-zero latency (local network), so introducing latency via internet connection results in problems, as the game-code was never tested for this.
> > 
> > 
> > Yep. That is what the bounty is for! If people can add online play to Smash Brothers Melee- a game that never had netcode to begin with- then I don't see why a game that already has netcode cannot have said netcode expanded to function correctly with higher pings
> 
> I think melee netplay just works by treating the game as a black box, just relaying controller inputs from one game to another, I'll consult with some tech savvy users to see if we can work out precise details.
> 
> In this sense, melee's approach is easier, since it doesn't necessitate the modification of any existing code. So taking advantage of the existing LAN code might be a red herring.
> 
> That said, netplay has been for a long time, it's likely that the naïve solution I'm describing has been developed over time incorporating game-specific optimizations, but I believe that melee netplay has worked for years based on some very simple underlying principle.

Slippi is more complicated than that if I recall correctly. it actually adds rollback net code. 

But that is actually how MKDD's netcode works. it only syncs controller data. the issue is the buffer is too small so it locks up.

**Comment by TZubiri** [comment]
Yes, I'm aware there's this new thing called slippy, that's what I was referring to when I mentioned a non-naïve solution that developed over time.

Now that I think of it, melee is usually played 1v1, so the traditional netplay might not translate neatly to the 12 players of mario kart.

**Comment by rolfen** [comment]
> I think melee netplay just works by treating the game as a black box, just relaying controller inputs from one game to another, I'll consult with some tech savvy users to see if we can work out precise details.

This would introduce lag in the controller, so if you press right for example it may take take a moment (depending on the connection latency) for the input to be reflected in the game.

Would such a side effect be acceptable in the solution to this bounty?

**Comment by abebeos** [comment]
@Sir-LoLz , after more than 2 years, there is still no requirements/feasibility/solution-path analysis. As stated last year, the task needs to be described better, possible solution-paths analyzed.

Such an analysis would eventually lead to the elimination of some solution-paths (e.g. by a visitor who reads through, and detects non-feasibility e.g. due to a tiny technical detail).

Work done so far would be added as Solutions and documented why it failed.


## Description

## Requirements

## Solution Paths

### Path A

* Take "tool x"
* patch "y"
* Patch "z"
* etc.

#### Benefits

#### Potential Problems

### Path B

**Comment by ghost** [comment]
The solution to this issue is more or less obvious from Sir-LoLz's description: hack the game code so that it keeps a copy of the last synced game state, have it skip waiting for lagging player inputs, then, once they actually arrive, have it do an inputs replay against the saved state, then update its copy.

That bit of wisdom and a 50¢ can buy you a can of coke. The actual complexity of making sense of the relevant code is, at least, a month or two of full-time work by a competent reverse engineer. I've actually spent a week this month trying to. The best I've figured is that yes, it's possible and feasible, but it's a ludicrous amount of work.

The only good news is that there is an ongoing MKDD decompilation project at its early stage, by one @SwareJonge. When, and if it will be finished, solving the issue will be trivial for any GC/Wii homebrewer. Whether they'll be interested in the bounty is anyone's guess, though.

Having said that, I'm signing off, never to return to the issue again.

**Comment by abebeos** [comment]
Again: do a decent requirements-analysis (https://github.com/Sir-LoLz/Improve-MKDD-netcode/issues/1#issuecomment-1398270447), present the analysis (including existent results) in a clear manner.

This way interested parties can get immediately an overview of the problem-domain, and come up with a solution that everyone else did not see.

(This is a standard-procedure, not much to discuss about it)

**Comment by Sir-LoLz** [comment]
I have come to this conclusion as well. I guess my hope was that with a symbol map, extending the lockstep buffer a few frames would be *easy* for someone that had an understanding of assembly. But I now realize that while maybe well-meaning was ultimately underestimating the reality of the situation. 

in the coming days as time allows I am going to try and implement the strategies mentioned above. I have also decided to start learning what I can about the process myself. Not going to keep pestering busy people with my niche interest. Won't ask someone to do something I would not do myself. 

Thanks for the feedback. And thanks for taking a look ghost.
